// <auto-generated />
namespace ClothingBazaar.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddedProdcutlsFeatured : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedProdcutlsFeatured));
        
        string IMigrationMetadata.Id
        {
            get { return "202002240116176_AddedProdcutlsFeatured"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
